branch-defaults:
  master:
    environment: sound
    group_suffix: null
global:
  application_name: sound
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
